### ISSUE TITLE
hope there will be paper repo of weekly workshop

### ISSUE THREAD

**Issue by PiotrNewt** [CDDSCLab/Database-Optimization#7]
hi, @IcePigZDB 
can you guys please sort out the papers shared every week to a new repo? this repo can be the sub-repo(link) of it.
like this one [db-readings](https://github.com/rxin/db-readings) (But it hasn't been maintained for a long time). **and as you know, DSCL does not just focus on databases**. 
This certainly has two advantages, I guess:
- for DSCL, new students can look through the relevant papers and brief descriptions, and quickly find the direction they are interested in. these papers have been classified, which is what we(when we joined the lab) expect to see
- for the community, more and more researchers and students can benefit from it, and even attract students who want to join us. over time, this is a win-win thing. 

and a little suggestion: is it better to use English to maintain a knowledge repo that is open to the community?

**Comment by IcePigZDB** [comment]
hi, @PiotrNewt 
Thank you very much for your detailed advice!
We will carefully discuss the feasibility of this proposal and the specific implementation plan. Follow-up plans will continue to be discussed here.
I strongly endorse the use of English to maintain this repository, not only to communicate with people from all over the world, but also to practice the communication skills of my labmates.

**Comment by PiotrNewt** [comment]
thank you for your reply and hope the plan goes smoothly!!
if need help, I will always be here

> hi, @PiotrNewt
> Thank you very much for your detailed advice!
> We will carefully discuss the feasibility of this proposal and the specific implementation plan. Follow-up plans will continue to be discussed here.
> I strongly endorse the use of English to maintain this repository, not only to communicate with people from all over the world, but also to practice the communication skills of my labmates.

**Comment by adlternative** [comment]
Hi! I see CDDSCLab's weekly storage/distribution paper sharing, It's just what I've been dreaming of. Are there opportunities for outsiders to join the CDDSCLab's study? :0

**Comment by PiotrNewt** [comment]
您好！您的邮件我已经收到，我会尽快查阅并处理。谢谢！I have received your email and I will review it and process it as soon as possible.  Thank you!                                                             -- Jian Yang

**Comment by ehds** [comment]
> there


@IcePigZDB  @huge-melon

**Comment by huge-melon** [comment]
I‘m sorry the weekly paper sharing is internal . We upload the shared paper and PPT every week at [Weekly-Group-Meeting-Paper-List](https://github.com/CDDSCLab/Weekly-Group-Meeting-Paper-List). If you have any questions, we'll try to answer them for you.

> Hi! I see CDDSCLab's weekly storage/distribution paper sharing, It's just what I've been dreaming of. Are there opportunities for outsiders to join the CDDSCLab's study? :0
